In [5]:
import os
import sys
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, optimizers, datasets

print('python version:', sys.version.split('\n')[0])
for m in [tf, np, pd, mpl]:
    print(m.__name__, 'version:', m.__version__)

python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 
tensorflow version: 2.3.1
numpy version: 1.18.5
pandas version: 1.1.3
matplotlib version: 3.3.2


# tf.constant
## data type

In [24]:
# scalar: dim = 0
a = tf.constant(2.8)
print('a:',a)

# vector: dim = 1
b = tf.constant([1.,2.,3.])
print('b:',b)

# matrix: dim>1
c = tf.constant([[1.,2.], [3.,4.]])
print('c:',c)

# String
d = tf.constant('Hello world')
print('d:',d)
print(tf.strings.upper(d))

# Bool
e = tf.constant(True)
print('e:',e)

# return numpy array
print(a.numpy())
print(b.numpy())
print(c.numpy())

a: tf.Tensor(2.8, shape=(), dtype=float32)
b: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
c: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
d: tf.Tensor(b'Hello world', shape=(), dtype=string)
tf.Tensor(b'HELLO WORLD', shape=(), dtype=string)
e: tf.Tensor(True, shape=(), dtype=bool)
2.8
[1. 2. 3.]
[[1. 2.]
 [3. 4.]]


## numerical precision

In [28]:
print(tf.constant(123456789, dtype=tf.int16))
print(tf.constant(123456789, dtype=tf.int32))

print(tf.constant(np.pi, dtype=tf.float32))
print(tf.constant(np.pi, dtype=tf.float64))

tf.Tensor(-13035, shape=(), dtype=int16)
tf.Tensor(123456789, shape=(), dtype=int32)
tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.141592653589793, shape=(), dtype=float64)


In [29]:
a = tf.constant(np.pi, dtype=tf.float16)
tf.cast(a, tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=3.140625>

# tf.Variable

In [34]:
a = tf.Variable([1.,2.,3.])
print(a)
print(a.name)
print(a.trainable)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
Variable:0
True


# creat a tensor

In [35]:
# from list or np.array
print(tf.convert_to_tensor([1.,2.,3.]))
print(tf.convert_to_tensor(np.array([4.,5.,6.])))

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([4. 5. 6.], shape=(3,), dtype=float64)


In [36]:
print(tf.zeros([3,2]))
print(tf.ones([3,2]))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [38]:
a = tf.constant([[1,2],[3,4]])
print(a)
print(tf.zeros_like(a)) # tf.zeros(a.shape)
print(tf.ones_like(a))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [39]:
tf.fill([3,2], -1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[-1, -1],
       [-1, -1],
       [-1, -1]], dtype=int32)>

In [42]:
# normal distridution
print(tf.random.normal([2,5], mean=0., stddev=1.))

# uniform distribution
print(tf.random.uniform([2,5], minval=0, maxval=10))

tf.Tensor(
[[-1.1221858  -0.26447788 -0.19432648  0.21492243 -0.8909105 ]
 [-0.21538912  0.36525288  0.2668972  -0.62355417 -1.3194455 ]], shape=(2, 5), dtype=float32)
tf.Tensor(
[[4.7485695e+00 6.6635456e+00 1.1197376e+00 9.4262991e+00 8.9299889e+00]
 [1.4094007e+00 2.0307064e-01 5.2933526e+00 5.1143694e+00 1.9884109e-03]], shape=(2, 5), dtype=float32)


In [43]:
tf.range(1,10,2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

# typical application

In [46]:
# compute loss

out = tf.random.uniform([4,10])
y = tf.constant([1,1,2,0])
y = tf.one_hot(y, depth=10)

loss = tf.keras.losses.mse(y, out)
print(loss)
print(tf.reduce_mean(loss))

tf.Tensor([0.23846166 0.27725846 0.48889145 0.29928493], shape=(4,), dtype=float32)
tf.Tensor(0.32597414, shape=(), dtype=float32)


In [49]:
# linear layer

x = tf.random.normal([2,4])
w = tf.ones([4,3])
b = tf.zeros([3])
o = x@w+b
print(o)

fc = layers.Dense(3) # 3 nodes
fc.build(input_shape=(2,4))
print(fc.kernel) # w

tf.Tensor(
[[-2.8929625  -2.8929625  -2.8929625 ]
 [-0.65515757 -0.65515757 -0.65515757]], shape=(2, 3), dtype=float32)
<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.5747014 ,  0.90568733,  0.1645335 ],
       [ 0.74360216,  0.40344596,  0.55422854],
       [ 0.7008624 ,  0.36358738,  0.20591736],
       [-0.7390164 ,  0.3078034 , -0.3821327 ]], dtype=float32)>


# index & slice

In [65]:
# 4 2*2 RGB 3 channel pictures [b,h,w,c]

x = tf.random.normal([4,2,2,3])

# the first picture, the first channel
print(x[0,::,::,0])
print(x[0,...,0])

tf.Tensor(
[[ 0.8802447  1.4221078]
 [-0.5304276 -0.2409979]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.8802447  1.4221078]
 [-0.5304276 -0.2409979]], shape=(2, 2), dtype=float32)


In [67]:
# reshape
print(tf.reshape(x, [4,-1]).shape) # [4,2,2,3] -> [4,12]
print(tf.reshape(x, [4,-1,3]).shape) # [4,2,2,3] -> [4,4,3]

(4, 12)
(4, 4, 3)


In [83]:
# add or remove dimension
x = tf.random.uniform([28,28], maxval=10, dtype=tf.int32)

print(tf.expand_dims(x, axis=0).shape)
print(tf.expand_dims(x, axis=1).shape)
print(tf.expand_dims(x, axis=-1).shape)

x = tf.expand_dims(x, axis=0)
print(tf.squeeze(x, axis=0).shape) # remove the dim=1

(1, 28, 28)
(28, 1, 28)
(28, 28, 1)
(28, 28)


In [84]:
# exchange dimension

x = tf.random.normal([4,5,6,7])

print(tf.transpose(x, perm=[3,2,1,0]).shape)

(7, 6, 5, 4)


In [93]:
# data duplicate

x = tf.constant([1,2,3])
print(x.shape)

x = tf.expand_dims(x, axis=0)
print(x.shape)

print(tf.tile(x, multiples=[3,2])) # duplicate 3 times in axis=0, 2 times in axis=1

(3,)
(1, 3)
tf.Tensor(
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]], shape=(3, 6), dtype=int32)


In [94]:
# broadcasting, more effective
# broadcast [w,1] to [b,h,w,c]
# 1. right justify: [_,_,w,1]
# 2. insert new dimension from left: [1,1,w,1]
# 3. dim=1 is expandable: [b,h,w,c]

x = tf.random.normal([32,1])
tf.broadcast_to(x, [4,32,32,3]).shape

TensorShape([4, 32, 32, 3])